# Generated by Django 4.0.6 on 2022-09-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_sales_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_sales_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sales_report',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
