# Generated by Django 4.0.6 on 2022-09-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
