# Generated by Django 4.0.6 on 2022-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_offer',
            name='offer_amount',
            field=models.IntegerField(default=0),
        ),
    ]
