# Generated by Django 4.0.6 on 2022-10-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
