# Generated by Django 4.0.6 on 2022-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='dis_amt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
