# Generated by Django 4.0.6 on 2022-09-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_savedaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out of delivery', 'Out of delivery'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Confirmed', max_length=50),
        ),
    ]
