# Generated by Django 4.0.6 on 2022-09-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_return_expiary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return_expiary',
        ),
    ]
